-- https://school.programmers.co.kr/learn/courses/30/lessons/131537

SELECT DATE_FORMAT(un.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, un.PRODUCT_ID, un.USER_ID, un.SALES_AMOUNT
FROM (
    (
        SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
        FROM OFFLINE_SALE 
        WHERE SALES_DATE BETWEEN DATE('2022-03-01') AND DATE('2022-03-31')
    )
    UNION ALL
    (
        SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM ONLINE_SALE 
        WHERE SALES_DATE BETWEEN DATE('2022-03-01') AND DATE('2022-03-31')
    )
) un
ORDER BY un.SALES_DATE, un.PRODUCT_ID, un.USER_ID
;