-- https://school.programmers.co.kr/learn/courses/30/lessons/132204

SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD, APNT_CNCL_YN
    FROM APPOINTMENT 
    WHERE MCDP_CD = "CS"
        AND APNT_CNCL_YN = "N"
        AND APNT_YMD BETWEEN DATE("2022-04-13") AND DATE("2022-04-14")
) A 
    LEFT JOIN PATIENT P ON A.PT_NO = P.PT_NO
    LEFT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD ASC
;